FROM node:16-alpine as build-stage
RUN apk --no-cache add python3 make g++ \
    && ln -sf python3 /usr/bin/python
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx:alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./nginx.staging.conf /etc/nginx/nginx.conf
EXPOSE 8180
CMD ["nginx", "-g", "daemon off;"]
