FROM node:alpine as build-stage
RUN apk --no-cache add openssl
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx:latest as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY ./nginx.staging.conf /etc/nginx/nginx.conf
EXPOSE 8180
